# -*- coding: utf-8 -*-
"""graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAsdSjo05ElZFSwfMiHwDnlR9W3LK9Rg
"""

import matplotlib.pyplot as plt
categories = ['Category B', 'Category C', 'Category D']
amounts = [25, 50, 30]
plt.bar(categories, amounts)
plt.xlabel('Categories')
plt.ylabel('Amounts')
plt.title('Bar Chart of Amounts by Category')
plt.show()

import matplotlib.pyplot as plt
categories = ['Category A', 'Category B', 'Category C']
amounts = [25, 50, 30]
plt.pie(amounts, labels=categories, autopct='%1.1f%%')
plt.title('Pie Chart of Amounts by Category')
plt.show()

import matplotlib.pyplot as plt
years = [2010, 2011, 2012, 2013, 2014]
amounts = [100, 120, 140, 110, 150]
plt.plot(years, amounts, marker='o', linestyle='-')
plt.xlabel('Year')
plt.ylabel('Amount')
plt.title('Line Chart of Amounts Over Time')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
x = [10, 20, 30, 40, 50]
y = [50, 40, 30, 20, 10]
plt.scatter(x, y)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Scatter Plot of X vs. Y')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
data = np.random.randn(1000)
plt.hist(data, bins=20, edgecolor='k')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram of Data')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
mu, sigma = 1, 5
data = np.random.normal(mu, sigma, 1000)
plt.hist(data, bins=30, color='y', edgecolor='k', alpha=0.7)
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram of a Normal Distribution')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
low, high = 0, 2
data = np.random.uniform(low, high, 1000)
plt.hist(data, bins=20, color='c', edgecolor='r', alpha=0.7)
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram of a Uniform Distribution')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
scale = 1.0
data = np.random.exponential(scale, 1000)
plt.hist(data, bins=20, edgecolor='k', alpha=0.7)
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram of an Exponential Distribution')
plt.grid(True)
plt.show()

import seaborn as sns
import numpy as np
mu, sigma = 1, 5
data = np.random.normal(mu, sigma, 1000)
sns.kdeplot(data, color='r', shade=True)
plt.xlabel('Value')
plt.ylabel('Density')
plt.title('Kernel Density Estimation (KDE) Plot of a Normal Distribution')
plt.show()